export default [
  {
    id: 1,
    firstName: 'Carlie',
    lastName: 'Wharlton',
    email: 'cwharlton0@unesco.org',
    shirtSize: '2XL',
  },
  {
    id: 2,
    firstName: 'Wye',
    lastName: 'Dreossi',
    email: 'wdreossi1@squarespace.com',
    shirtSize: '2XL',
  },
  {
    id: 3,
    firstName: 'Darcee',
    lastName: 'Rigmond',
    email: 'drigmond2@sakura.ne.jp',
    shirtSize: 'L',
  },
  {
    id: 4,
    firstName: 'Ole',
    lastName: 'Hains',
    email: 'ohains3@over-blog.com',
    shirtSize: 'L',
  },
  {
    id: 5,
    firstName: 'Frasier',
    lastName: 'Seagrove',
    email: 'fseagrove4@e-recht24.de',
    shirtSize: 'XS',
  },
  {
    id: 6,
    firstName: 'Kaitlynn',
    lastName: 'Dwelly',
    email: 'kdwelly5@state.gov',
    shirtSize: '2XL',
  },
  {
    id: 7,
    firstName: 'Budd',
    lastName: 'Wilber',
    email: 'bwilber6@tinypic.com',
    shirtSize: 'XS',
  },
  {
    id: 8,
    firstName: 'Flynn',
    lastName: 'Umbers',
    email: 'fumbers7@hud.gov',
    shirtSize: 'M',
  },
  {
    id: 9,
    firstName: 'Gelya',
    lastName: 'Minney',
    email: 'gminney8@comcast.net',
    shirtSize: 'XL',
  },
  {
    id: 10,
    firstName: 'Sophronia',
    lastName: 'Shill',
    email: 'sshill9@uol.com.br',
    shirtSize: 'XL',
  },
]
